trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: pipelineTasksPath
    value: pipeline/tasks
  - group: tapacr

steps:
- script: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.27.0/pack-v0.27.0-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)

- bash: $(pipelineTasksPath)/00-login-to-cr.sh
  displayName: Login to CR
  failOnStderr: true
  env:
    CR_NAME: $(tapacr_name)
    CR_USER: $(tapacr_username)
    CR_PASS: $(tapacr_password)

- bash: $(pipelineTasksPath)/01-package-buildpack.sh
  displayName: Create buildpack
  failOnStderr: true

- bash: $(pipelineTasksPath)/02-create-stack.sh
  displayName: Create stack
  failOnStderr: true

- bash: $(pipelineTasksPath)/03-create-builder.sh
  displayName: Create builder
  failOnStderr: true
